# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/xud/bscan

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/xud/bscan

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xud/bscan/CMakeFiles /home/xud/bscan/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xud/bscan/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ./bin/bscan

# Build rule for target.
./bin/bscan: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ./bin/bscan
.PHONY : ./bin/bscan

# fast build rule for target.
./bin/bscan/fast:
	$(MAKE) -f CMakeFiles/./bin/bscan.dir/build.make CMakeFiles/./bin/bscan.dir/build
.PHONY : ./bin/bscan/fast

src/blist.o: src/blist.c.o
.PHONY : src/blist.o

# target to build an object file
src/blist.c.o:
	$(MAKE) -f CMakeFiles/./bin/bscan.dir/build.make CMakeFiles/./bin/bscan.dir/src/blist.c.o
.PHONY : src/blist.c.o

src/blist.i: src/blist.c.i
.PHONY : src/blist.i

# target to preprocess a source file
src/blist.c.i:
	$(MAKE) -f CMakeFiles/./bin/bscan.dir/build.make CMakeFiles/./bin/bscan.dir/src/blist.c.i
.PHONY : src/blist.c.i

src/blist.s: src/blist.c.s
.PHONY : src/blist.s

# target to generate assembly for a file
src/blist.c.s:
	$(MAKE) -f CMakeFiles/./bin/bscan.dir/build.make CMakeFiles/./bin/bscan.dir/src/blist.c.s
.PHONY : src/blist.c.s

src/bscan.o: src/bscan.c.o
.PHONY : src/bscan.o

# target to build an object file
src/bscan.c.o:
	$(MAKE) -f CMakeFiles/./bin/bscan.dir/build.make CMakeFiles/./bin/bscan.dir/src/bscan.c.o
.PHONY : src/bscan.c.o

src/bscan.i: src/bscan.c.i
.PHONY : src/bscan.i

# target to preprocess a source file
src/bscan.c.i:
	$(MAKE) -f CMakeFiles/./bin/bscan.dir/build.make CMakeFiles/./bin/bscan.dir/src/bscan.c.i
.PHONY : src/bscan.c.i

src/bscan.s: src/bscan.c.s
.PHONY : src/bscan.s

# target to generate assembly for a file
src/bscan.c.s:
	$(MAKE) -f CMakeFiles/./bin/bscan.dir/build.make CMakeFiles/./bin/bscan.dir/src/bscan.c.s
.PHONY : src/bscan.c.s

src/htmlp.o: src/htmlp.c.o
.PHONY : src/htmlp.o

# target to build an object file
src/htmlp.c.o:
	$(MAKE) -f CMakeFiles/./bin/bscan.dir/build.make CMakeFiles/./bin/bscan.dir/src/htmlp.c.o
.PHONY : src/htmlp.c.o

src/htmlp.i: src/htmlp.c.i
.PHONY : src/htmlp.i

# target to preprocess a source file
src/htmlp.c.i:
	$(MAKE) -f CMakeFiles/./bin/bscan.dir/build.make CMakeFiles/./bin/bscan.dir/src/htmlp.c.i
.PHONY : src/htmlp.c.i

src/htmlp.s: src/htmlp.c.s
.PHONY : src/htmlp.s

# target to generate assembly for a file
src/htmlp.c.s:
	$(MAKE) -f CMakeFiles/./bin/bscan.dir/build.make CMakeFiles/./bin/bscan.dir/src/htmlp.c.s
.PHONY : src/htmlp.c.s

src/spider.o: src/spider.c.o
.PHONY : src/spider.o

# target to build an object file
src/spider.c.o:
	$(MAKE) -f CMakeFiles/./bin/bscan.dir/build.make CMakeFiles/./bin/bscan.dir/src/spider.c.o
.PHONY : src/spider.c.o

src/spider.i: src/spider.c.i
.PHONY : src/spider.i

# target to preprocess a source file
src/spider.c.i:
	$(MAKE) -f CMakeFiles/./bin/bscan.dir/build.make CMakeFiles/./bin/bscan.dir/src/spider.c.i
.PHONY : src/spider.c.i

src/spider.s: src/spider.c.s
.PHONY : src/spider.s

# target to generate assembly for a file
src/spider.c.s:
	$(MAKE) -f CMakeFiles/./bin/bscan.dir/build.make CMakeFiles/./bin/bscan.dir/src/spider.c.s
.PHONY : src/spider.c.s

src/urlqueue.o: src/urlqueue.c.o
.PHONY : src/urlqueue.o

# target to build an object file
src/urlqueue.c.o:
	$(MAKE) -f CMakeFiles/./bin/bscan.dir/build.make CMakeFiles/./bin/bscan.dir/src/urlqueue.c.o
.PHONY : src/urlqueue.c.o

src/urlqueue.i: src/urlqueue.c.i
.PHONY : src/urlqueue.i

# target to preprocess a source file
src/urlqueue.c.i:
	$(MAKE) -f CMakeFiles/./bin/bscan.dir/build.make CMakeFiles/./bin/bscan.dir/src/urlqueue.c.i
.PHONY : src/urlqueue.c.i

src/urlqueue.s: src/urlqueue.c.s
.PHONY : src/urlqueue.s

# target to generate assembly for a file
src/urlqueue.c.s:
	$(MAKE) -f CMakeFiles/./bin/bscan.dir/build.make CMakeFiles/./bin/bscan.dir/src/urlqueue.c.s
.PHONY : src/urlqueue.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... ./bin/bscan"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/blist.o"
	@echo "... src/blist.i"
	@echo "... src/blist.s"
	@echo "... src/bscan.o"
	@echo "... src/bscan.i"
	@echo "... src/bscan.s"
	@echo "... src/htmlp.o"
	@echo "... src/htmlp.i"
	@echo "... src/htmlp.s"
	@echo "... src/spider.o"
	@echo "... src/spider.i"
	@echo "... src/spider.s"
	@echo "... src/urlqueue.o"
	@echo "... src/urlqueue.i"
	@echo "... src/urlqueue.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

